[package]
name = "klotski"
version = "0.0.2"
edition = "2021"
authors = ["Dnomd343 <dnomd343@gmail.com>"]
description = "Klotski multifunctional engine with high performance"
categories = ["algorithms", "science", "games", "external-ffi-bindings"]
repository = "https://github.com/dnomd343/klotski"
license = "BSD-3-Clause"
readme = "README.md"

# TODO: add `homepage` and `documentation`

exclude = [
  "/CMakeLists.txt",
  "/klotski/src/core/main.cc",
  "/klotski/src/core/benchmark/",
  #"/klotski/src/core/utils/metadata.h",  # TODO: code generated in crate dir is not allowed in cargo.

  "klotski/third_party/parallel-hashmap/*",
  "!klotski/third_party/parallel-hashmap/cmake/",
  "!klotski/third_party/parallel-hashmap/LICENSE",
  "!klotski/third_party/parallel-hashmap/CMakeLists.txt",
  "!klotski/third_party/parallel-hashmap/parallel_hashmap/",
]

[profile.release]
lto = "fat"
panic = "abort"

# TODO: also for `profile.test` and `profile.bench`

[dependencies]
cxx = { version = "1.0", features = ["c++20"] }

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"
