[package]
name = "klotski_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rust-crypto = "0.2.36"

[build-dependencies]
bindgen = "0.64.0"
